"""
JARVIS-OS First-Launch Setup — Interactive API key configuration.
Runs on first boot when no API keys are configured, also accessible
from the dashboard Settings at any time.
"""

import os
import sys
from pathlib import Path
from getpass import getpass

ROOT_DIR = Path(__file__).parent


def get_env_path() -> Path:
    return ROOT_DIR / ".env"


def load_env() -> dict:
    """Load existing .env key-value pairs."""
    env_path = get_env_path()
    env = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                env[key.strip()] = value.strip()
    return env


def save_env(env: dict):
    """Save key-value pairs to .env file."""
    env_path = get_env_path()
    lines = [
        "# JARVIS-OS Environment Configuration",
        "# Auto-generated by setup wizard\n",
    ]
    for k, v in env.items():
        lines.append(f"{k}={v}")
    env_path.write_text("\n".join(lines) + "\n")


def apply_env(env: dict):
    """Apply env vars to the current process."""
    for k, v in env.items():
        if v:
            os.environ[k] = v


def has_api_keys() -> bool:
    """Check if at least one API key is configured."""
    env = load_env()
    openai_key = env.get("OPENAI_API_KEY", "") or os.environ.get("OPENAI_API_KEY", "")
    anthropic_key = env.get("ANTHROPIC_API_KEY", "") or os.environ.get("ANTHROPIC_API_KEY", "")
    return bool(openai_key and not openai_key.startswith("sk-your")) or \
           bool(anthropic_key and not anthropic_key.startswith("sk-ant-your"))


def run_terminal_setup():
    """Interactive terminal-based setup wizard for first launch."""
    print()
    print("=" * 60)
    print("  JARVIS-OS — First Launch Setup")
    print("=" * 60)
    print()
    print("  JARVIS needs at least one LLM API key to function.")
    print("  You can configure more later in Settings.")
    print()

    env = load_env()

    # Provider choice
    print("  Which LLM provider would you like to use?")
    print("    1) OpenAI  (GPT-4o)")
    print("    2) Anthropic  (Claude)")
    print("    3) Both")
    print()

    choice = ""
    while choice not in ("1", "2", "3"):
        choice = input("  Enter choice [1/2/3]: ").strip()

    if choice in ("1", "3"):
        print()
        key = getpass("  Enter your OpenAI API key (hidden): ").strip()
        if key:
            env["OPENAI_API_KEY"] = key
            os.environ["OPENAI_API_KEY"] = key
            print("  OpenAI key saved.")

    if choice in ("2", "3"):
        print()
        key = getpass("  Enter your Anthropic API key (hidden): ").strip()
        if key:
            env["ANTHROPIC_API_KEY"] = key
            os.environ["ANTHROPIC_API_KEY"] = key
            print("  Anthropic key saved.")

    save_env(env)
    apply_env(env)

    print()
    print("  Configuration saved to .env")
    print("  You can change this anytime in the JARVIS-OS Settings app.")
    print()
    print("=" * 60)
    print("  Starting JARVIS-OS...")
    print("=" * 60)
    print()


def save_api_key(provider: str, api_key: str) -> dict:
    """Save a single API key (called from the dashboard)."""
    env = load_env()

    if provider == "openai":
        if not api_key.startswith("sk-"):
            return {"status": "error", "message": "OpenAI keys must start with sk-"}
        env["OPENAI_API_KEY"] = api_key
        os.environ["OPENAI_API_KEY"] = api_key
    elif provider == "anthropic":
        if not api_key.startswith("sk-ant-"):
            return {"status": "error", "message": "Anthropic keys must start with sk-ant-"}
        env["ANTHROPIC_API_KEY"] = api_key
        os.environ["ANTHROPIC_API_KEY"] = api_key
    else:
        return {"status": "error", "message": f"Unknown provider: {provider}"}

    save_env(env)
    return {"status": "success", "message": f"{provider.title()} API key saved successfully"}


def get_masked_keys() -> dict:
    """Return masked versions of configured API keys for display."""
    env = load_env()
    openai_key = env.get("OPENAI_API_KEY", "") or os.environ.get("OPENAI_API_KEY", "")
    anthropic_key = env.get("ANTHROPIC_API_KEY", "") or os.environ.get("ANTHROPIC_API_KEY", "")

    def mask(key: str) -> str:
        if not key or key.startswith("sk-your") or key.startswith("sk-ant-your"):
            return ""
        if len(key) > 12:
            return key[:6] + "..." + key[-4:]
        return "***"

    return {
        "openai": mask(openai_key),
        "anthropic": mask(anthropic_key),
    }


def get_configured_providers() -> dict:
    """Check which providers have keys configured."""
    env = load_env()
    openai_key = env.get("OPENAI_API_KEY", "") or os.environ.get("OPENAI_API_KEY", "")
    anthropic_key = env.get("ANTHROPIC_API_KEY", "") or os.environ.get("ANTHROPIC_API_KEY", "")

    return {
        "openai": bool(openai_key and not openai_key.startswith("sk-your")),
        "anthropic": bool(anthropic_key and not anthropic_key.startswith("sk-ant-your")),
        "any_configured": bool(openai_key and not openai_key.startswith("sk-your")) or
                          bool(anthropic_key and not anthropic_key.startswith("sk-ant-your")),
    }
