"""
JARVIS-OS Plugin Manager — Self-expanding plugin system.
JARVIS can create, load, and manage its own plugins to evolve its capabilities.
"""

import importlib
import importlib.util
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger("jarvis.plugins")

# Plugin template that JARVIS uses to create new plugins
PLUGIN_TEMPLATE = '''"""
JARVIS-OS Plugin: {name}
{description}

Auto-generated by JARVIS-OS Evolution System.
"""

PLUGIN_INFO = {{
    "name": "{name}",
    "version": "1.0.0",
    "description": "{description}",
    "author": "JARVIS-OS",
    "capabilities": {capabilities},
}}


def get_tools():
    """Return tool definitions that agents can use."""
    return [
        {{
            "name": "{tool_name}",
            "description": "{description}",
            "parameters": {{
                "type": "object",
                "properties": {{}},
            }},
        }}
    ]


async def execute(tool_name: str, arguments: dict, context: dict) -> dict:
    """Execute a tool call from this plugin."""
    # TODO: Implement tool logic
    return {{"status": "success", "result": "Plugin executed"}}


async def on_load(kernel):
    """Called when the plugin is loaded."""
    pass


async def on_unload():
    """Called when the plugin is unloaded."""
    pass
'''


class Plugin:
    """Represents a loaded plugin."""
    def __init__(self, name: str, path: Path, module=None):
        self.name = name
        self.path = path
        self.module = module
        self.info = {}
        self.enabled = True
        self.loaded_at = datetime.now()
        self.tools = []

        if module and hasattr(module, 'PLUGIN_INFO'):
            self.info = module.PLUGIN_INFO
        if module and hasattr(module, 'get_tools'):
            self.tools = module.get_tools()

    def to_dict(self):
        return {
            "name": self.name,
            "path": str(self.path),
            "info": self.info,
            "enabled": self.enabled,
            "loaded_at": self.loaded_at.isoformat(),
            "tools": [t["name"] for t in self.tools],
            "description": self.info.get("description", ""),
        }


class PluginManager:
    """
    Manages plugin lifecycle: discovery, loading, execution, and creation.
    JARVIS can call create_plugin() to evolve itself with new capabilities.
    """

    def __init__(self, config: dict):
        self.config = config
        self.plugin_dir = Path(config.get("plugins", {}).get("plugin_dir", "./plugins"))
        self.plugin_dir.mkdir(parents=True, exist_ok=True)
        self.plugins: dict[str, Plugin] = {}
        self.kernel = None
        self._registry_path = self.plugin_dir / "registry.json"
        self._registry = self._load_registry()

    def _load_registry(self) -> dict:
        if self._registry_path.exists():
            try:
                return json.loads(self._registry_path.read_text())
            except Exception:
                return {}
        return {}

    def _save_registry(self):
        self._registry_path.write_text(json.dumps(self._registry, indent=2, default=str))

    async def initialize(self, kernel):
        self.kernel = kernel
        # Auto-discover and load plugins
        if self.config.get("plugins", {}).get("auto_discover", True):
            await self.discover_and_load()

    async def shutdown(self):
        for plugin in self.plugins.values():
            if plugin.module and hasattr(plugin.module, 'on_unload'):
                try:
                    await plugin.module.on_unload()
                except Exception as e:
                    logger.error(f"Plugin {plugin.name} unload error: {e}")

    async def discover_and_load(self):
        """Scan the plugin directory and load all valid plugins."""
        count = 0
        for path in self.plugin_dir.iterdir():
            if path.is_file() and path.suffix == '.py' and path.name != '__init__.py' and path.name != 'manager.py':
                try:
                    await self.load_plugin(path)
                    count += 1
                except Exception as e:
                    logger.error(f"Failed to load plugin {path.name}: {e}")
            elif path.is_dir() and (path / '__init__.py').exists():
                try:
                    await self.load_plugin(path / '__init__.py')
                    count += 1
                except Exception as e:
                    logger.error(f"Failed to load plugin {path.name}: {e}")

        logger.info(f"Loaded {count} plugins")

    async def load_plugin(self, path: Path) -> Plugin:
        """Load a single plugin from a file path."""
        name = path.stem if path.name != '__init__.py' else path.parent.name
        if name in self.plugins:
            return self.plugins[name]

        spec = importlib.util.spec_from_file_location(f"jarvis_plugin_{name}", str(path))
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)

        plugin = Plugin(name, path, module)
        self.plugins[name] = plugin

        # Call on_load
        if hasattr(module, 'on_load'):
            await module.on_load(self.kernel)

        # Register in registry
        self._registry[name] = {
            "path": str(path),
            "loaded_at": datetime.now().isoformat(),
            "info": plugin.info,
        }
        self._save_registry()

        logger.info(f"Plugin loaded: {name} — {len(plugin.tools)} tools")
        return plugin

    async def execute_plugin_tool(self, plugin_name: str, tool_name: str, arguments: dict) -> dict:
        """Execute a tool from a specific plugin."""
        plugin = self.plugins.get(plugin_name)
        if not plugin or not plugin.enabled:
            return {"error": f"Plugin not found or disabled: {plugin_name}"}

        if hasattr(plugin.module, 'execute'):
            context = {"kernel": self.kernel}
            return await plugin.module.execute(tool_name, arguments, context)

        return {"error": f"Plugin {plugin_name} has no execute function"}

    def get_all_plugin_tools(self) -> list:
        """Get all tools from all enabled plugins."""
        tools = []
        for plugin in self.plugins.values():
            if plugin.enabled:
                for tool in plugin.tools:
                    tool_copy = dict(tool)
                    tool_copy["_plugin"] = plugin.name
                    tools.append(tool_copy)
        return tools

    async def create_plugin(self, name: str, description: str, capabilities: list = None, code: str = None) -> dict:
        """
        JARVIS self-evolution: Create a new plugin dynamically.
        If code is provided, use it directly. Otherwise, generate from template.
        """
        safe_name = "".join(c if c.isalnum() or c == '_' else '_' for c in name.lower())
        plugin_path = self.plugin_dir / f"{safe_name}.py"

        if plugin_path.exists():
            return {"error": f"Plugin '{safe_name}' already exists"}

        if code:
            plugin_content = code
        else:
            tool_name = f"{safe_name}_execute"
            plugin_content = PLUGIN_TEMPLATE.format(
                name=name,
                description=description,
                capabilities=json.dumps(capabilities or []),
                tool_name=tool_name,
            )

        plugin_path.write_text(plugin_content)
        logger.info(f"Plugin created: {safe_name} at {plugin_path}")

        # Load the new plugin
        try:
            plugin = await self.load_plugin(plugin_path)
            return {
                "status": "success",
                "plugin": plugin.to_dict(),
                "message": f"Plugin '{name}' created and loaded successfully",
            }
        except Exception as e:
            return {"status": "error", "message": f"Plugin created but failed to load: {e}"}

    def unload_plugin(self, name: str) -> dict:
        plugin = self.plugins.get(name)
        if not plugin:
            return {"error": f"Plugin not found: {name}"}
        plugin.enabled = False
        return {"status": "success", "message": f"Plugin '{name}' disabled"}

    def get_all_plugins(self) -> list:
        return [p.to_dict() for p in self.plugins.values()]
