"""
JARVIS-OS Plugin: Web Search
Allows JARVIS agents to search the web for real-time information.

Auto-generated by JARVIS-OS Evolution System.
"""

import logging

logger = logging.getLogger("jarvis.plugin.web_search")

PLUGIN_INFO = {
    "name": "Web Search",
    "version": "1.0.0",
    "description": "Search the web for real-time information using DuckDuckGo",
    "author": "JARVIS-OS",
    "capabilities": ["web_search", "url_fetch"],
}


def get_tools():
    return [
        {
            "name": "web_search",
            "description": "Search the web using DuckDuckGo for real-time information.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {"type": "string", "description": "The search query"},
                    "max_results": {"type": "integer", "description": "Max results to return (default 5)"},
                },
                "required": ["query"],
            },
        },
        {
            "name": "fetch_url",
            "description": "Fetch the content of a URL.",
            "parameters": {
                "type": "object",
                "properties": {
                    "url": {"type": "string", "description": "The URL to fetch"},
                },
                "required": ["url"],
            },
        },
    ]


async def execute(tool_name: str, arguments: dict, context: dict) -> dict:
    if tool_name == "web_search":
        return await _web_search(arguments.get("query", ""), arguments.get("max_results", 5))
    elif tool_name == "fetch_url":
        return await _fetch_url(arguments.get("url", ""))
    return {"error": f"Unknown tool: {tool_name}"}


async def _web_search(query: str, max_results: int = 5) -> dict:
    try:
        import httpx
        async with httpx.AsyncClient(timeout=15) as client:
            response = await client.get(
                "https://html.duckduckgo.com/html/",
                params={"q": query},
                headers={"User-Agent": "JARVIS-OS/1.0"},
            )
            # Basic parsing of DuckDuckGo HTML results
            text = response.text
            results = []
            # Simple extraction of result snippets
            import re
            links = re.findall(r'<a rel="nofollow" class="result__a" href="([^"]+)">(.+?)</a>', text)
            snippets = re.findall(r'<a class="result__snippet"[^>]*>(.+?)</a>', text)

            for i, (url, title) in enumerate(links[:max_results]):
                result = {
                    "title": re.sub(r'<[^>]+>', '', title).strip(),
                    "url": url,
                    "snippet": re.sub(r'<[^>]+>', '', snippets[i]).strip() if i < len(snippets) else "",
                }
                results.append(result)

            return {"status": "success", "results": results, "query": query}
    except Exception as e:
        return {"status": "error", "message": str(e)}


async def _fetch_url(url: str) -> dict:
    try:
        import httpx
        async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
            response = await client.get(url, headers={"User-Agent": "JARVIS-OS/1.0"})
            content = response.text[:5000]  # Limit content
            return {
                "status": "success",
                "url": str(response.url),
                "status_code": response.status_code,
                "content": content,
            }
    except Exception as e:
        return {"status": "error", "message": str(e)}


async def on_load(kernel):
    logger.info("Web Search plugin loaded")


async def on_unload():
    logger.info("Web Search plugin unloaded")
